# Generated by Django 5.1.5 on 2025-07-22 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del formulario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(blank=True, null=True, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('firma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='TaskFlow.formulario', verbose_name='Formulario asociado')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='TaskFlow.formulario', verbose_name='Formulario asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de referencia')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie')),
                ('capacidad', models.CharField(max_length=100, verbose_name='Capacidad')),
                ('division_escala', models.CharField(max_length=100, verbose_name='División de escala')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='TaskFlow.formulario', verbose_name='Formulario asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del repuesto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del repuesto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='TaskFlow.formulario', verbose_name='Formulario asociado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50, unique=True, verbose_name='Nombre del servicio')),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_servicio', to='TaskFlow.formulario', verbose_name='Formulario asociado')),
            ],
        ),
    ]
