# Generated by Django 5.1.5 on 2025-07-27 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskFlow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='nombre_servicio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='firma_cliente',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='firma_tecnico',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='usuario_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_soporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(default='sinnombre', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='nombre',
            field=models.CharField(default='sinombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ClienteSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'nombre_sede')},
            },
        ),
        migrations.CreateModel(
            name='FormularioRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.IntegerField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.formulario')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.estadoservicios')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.clientesede')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.tiposervicio')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TaskFlow.solicitud'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FormularioDetalle',
        ),
        migrations.DeleteModel(
            name='Referencia',
        ),
    ]
