# Generated by Django 5.1.5 on 2025-08-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskFlow', '0002_estadoservicios_remove_referencia_formulario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='sede',
        ),
    ]
