# Generated by Django 5.1.5 on 2025-08-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskFlow', '0004_solicitud_usuario_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
